export const PVCcpData =[
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    }
]
export const FinolexData =[

    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
]
export const sudhakarData =[
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    }
]
export const NandiData =[
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    }
]
export const SupreemData=[
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    }
]
export const AhirvadData =[
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
    {
        "id": "",
        "image": "",
        "productname": "",
        "discription": "",
        "size": "",
        "length": "",
        "brand": "",
    },
]